<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html lang="en">

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<title>RSA In JavaScript - Decrypt - ohdave.com</title>

<?php

// Encryption exponent and modulus generated via
// openssl genrsa -out private_key.pem 2048
$private_key = '-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDuu/GMMeBTHi7O
7Z0keuvh47439KEFYhgYq7O/ddrNw9t9O80uJ54JzoGv0s0xPIoZlDS2yMokU0Aj
Tt1sv2vV/DT1giXrsB/s1HJHpm8kDtBszI6cfCDHbuVSv+O3kH31NrFBteoHrzg5
dsXtAhqSzSdNpSON88jEIIdT2GKSL6J8IRGg6kPlODd67hoxQOB8OwuAMDvZ1qCE
G9jdkcZI//lt39JxFfrop0D+vnMHQAedhwintXK0/60fVURwuFxi6PxRYKC0S4S/
7HpEtkBVCrqrerfuQzNvROCBQIzyjCLao9JxCSPCdiHgd0jas8fNGmick7/k9Iwc
MdQBoxwJAgMBAAECggEBAI7Aa0s9d7m7zpmFk/WAWxQTrmafLLmfUnFOGold25w2
hUR5QdNbdTC//uQ31OKgJKPu7yZtIhJehXeXbOfd/olR6gjz7eDky/I9hqg5aTPS
d+bW2l/QCXm3YgD9JRlamTbLoWp9cJdvutsBnpB+NY2ahuny2TPElkRQfxsvxKFM
GuDuujt7fo2wLYed0c6iggkgDu0Ojv6EDtIqlXPwb6edjUBxhTD/KnPYVX7XFxk4
IQoCyl5lP/4LUBym86n06Dt3ir7I1wBOWMVroKWBhaJu8d16CXACZ5aIlahJuQnN
dWR2VC7Bqcd9TVcDeol7d7LAIK/CsF/B1k8pbVJurUECgYEA+H2aD4UlO/vEnX/h
iTNahfm89IWs46gxBxosR9nNpqwXdm57hK1MROArZQVRxDBlUT93gnI0nUQD3y+X
axV8fxQ+dWq9ZqFBQaM9X7V7zvfvWUK7IuVUAiTkCyIcn8XFk4cDXAp/XiAv6ewc
qnSbuI+KYjmuPvX8FcHsAB/ceW0CgYEA9fLc2iqtyaKldqdU1XoLJA5oS/ANGpjy
XJ6vGuosDAPGpBeEqzDapa6TrnXhSl2dNnHlD07GHbkHoKBjuRsAYJWPO3knW1tp
oZnstLISeAb6KrBzcfRYNqQinZqDRI7nwDRFp6zr6hq93U5Q1fjUWQtkrZ81q8V8
sexsDahDR40CgYBZ5DYDP0tE88Mgps5T77vjk4CDhIgSoxl5VEKIi4YVsVObiEQu
rvJUSDPqi44Uxt0gEzGMgvv9mEk+R90i49bxscUWfNKfed49fGwLX3+2U4LGa5l+
+i71x5qnXGO2eLkMsV7JwRJqXoJ2wO9tylk63tJUzkD2jc3voQNa2CvN0QKBgCSi
kmck6FIamg78idRqo3IxezOkhC8sDR3ivS6DJyB7B4G1xxtA4bDAOltIT9Cl9R8B
BB+tmjEfOJWijngqH3pDjNxNBaHEEg3yQaIAzGN4lpb5RZj5zpIFDOrw8xCpQLgO
kTmStmlepl1qpvvYXrkMy2hZSMNXXWWbU9UM9UiZAoGBAJi7tjbEkkPiT8iD5T4q
fpPxC/8LNkSIUdGnvt3MCgzmgqI+lZ941g971/fQqcNiHOJ+dADfvNcLIyUty15d
noV9HVWL0g0t/r4+yAU+as1l05uyQfSF9wYghDmKCVRr3ldKedE8T534wPvvXirL
oWMBc8dtHFA7TMDpXLAMAS/r
-----END PRIVATE KEY-----';//私钥
$public_key="-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7rvxjDHgUx4uzu2dJHrr
4eO+N/ShBWIYGKuzv3XazcPbfTvNLieeCc6Br9LNMTyKGZQ0tsjKJFNAI07dbL9r
1fw09YIl67Af7NRyR6ZvJA7QbMyOnHwgx27lUr/jt5B99TaxQbXqB684OXbF7QIa
ks0nTaUjjfPIxCCHU9hiki+ifCERoOpD5Tg3eu4aMUDgfDsLgDA72daghBvY3ZHG
SP/5bd/ScRX66KdA/r5zB0AHnYcIp7VytP+tH1VEcLhcYuj8UWCgtEuEv+x6RLZA
VQq6q3q37kMzb0TggUCM8owi2qPScQkjwnYh4HdI2rPHzRponJO/5PSMHDHUAaMc
CQIDAQAB
-----END PUBLIC KEY-----";//公钥
$public_key_module="EEBBF18C31E0531E2ECEED9D247AEBE1E3BE37F4A105621818ABB3BF75DACDC3DB7D3BCD2E279E09CE81AFD2CD313C8A199434B6C8CA245340234EDD6CBF6BD5FC34F58225EBB01FECD47247A66F240ED06CCC8E9C7C20C76EE552BFE3B7907DF536B141B5EA07AF383976C5ED021A92CD274DA5238DF3C8C4208753D862922FA27C2111A0EA43E538377AEE1A3140E07C3B0B80303BD9D6A0841BD8DD91C648FFF96DDFD27115FAE8A740FEBE730740079D8708A7B572B4FFAD1F554470B85C62E8FC5160A0B44B84BFEC7A44B640550ABAAB7AB7EE43336F44E081408CF28C22DAA3D2710923C27621E07748DAB3C7CD1A689C93BFE4F48C1C31D401A31C09";//公钥模数
//$private_key = openssl_pkey_get_private('file://private_key.pem');
$private_key = openssl_pkey_get_private($private_key);

// ciphertext generated by JavaScript uses PKCS1 padding, emitted as base-64 string...
$ciphertext = $_POST['ciphertext'];
// ...convert to binary.
$bin_ciphertext = base64_decode($ciphertext);

openssl_private_decrypt($bin_ciphertext, $plaintext, $private_key, OPENSSL_PKCS1_PADDING)
	or die("openssl_private_decrypt failed.");

?>

</head>

<body>

<form>
	Ciphertext:<br />
	<textarea rows=8 cols=64 name="txtCiphertext"><?= $ciphertext ?></textarea>
	<br />
	<br />
	Plaintext:<br />
	<textarea rows=8 cols=64 name="txtPlaintext"><?= $plaintext ?></textarea>
</form>

<div>
	<a href="decrypt.php.txt">This page's source.</a>
</div>

<br>

<div>
	<a href="index.php">Return to main RSA page</a>
</div>

</body>

</html>
